# load the common Makefile.include for bearpi-l431rc boards
INCLUDES += -I$(RIOTBOARD)/common/stm32/include

# Setup of programmer and serial is shared between STM32 based boards
include $(RIOTMAKE)/boards/stm32.inc.mk
